#!/bin/bash
#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: Addition to OpenFOAM v6
#  \\    /   O peration     | Website:  https://github.com/StasF1/intakePipe
#   \\  /    A nd           | Copyright (C) 2018-2020 Stanislau Stasheuski
#    \\/     M anipulation  |
#------------------------------------------------------------------------------# License
#     This file is not part of OpenFOAM, but part of intakePipe – OpenFOAM
#     addition.
#
#     intakePipe (like OpenFOAM) is free software: you can redistribute it 
#     and/or modify it under the terms of the GNU General Public License as
#     published by the Free Software Foundation, either version 3 of the License,
#     or (at your option) any later version.
#   
#     intakePipe (like OpenFOAM) is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU General Public License for more details.
#   
#     You should have received a copy of the GNU General Public License
#     along with this repository. If not, see <http://www.gnu.org/licenses/>
#
# File
#     makeStrokes
#
# Description
#     Run version (variant) of the inlet channel geometry with a valve stroke
#     increase by a step
#
#------------------------------------------------------------------------------
cd ${0%/*} || exit 1    # Run from this directory

source ../strokeDict

# Create valve strokes cases
h=$strokeStart
while [ $h -le $strokeEnd ]
do
    # Convert [mm]->[m] for the stroke variable
    strokeMetres=`echo "scale=3; $h*10^(-3)" | bc -l`

    # Create stroke folder by copying the stroke_0mm/ folder
    mkdir -p stroke_${h}mm && cp -a stroke_0mm/* stroke_${h}mm

    #- Set stroke
    sed -i "s/strokeMetres/$strokeMetres/g" stroke_${h}mm/Allmesh

    h=`echo "scale=1; $h + $strokeDelta" | bc`
done

#------------------------------------------------------------------------------