#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh

#- Run serial
# runApplication $(getApplication)

#- Run parallel
runApplication decomposePar -force
runParallel $(getApplication)
runApplication reconstructPar -latestTime -fields\
    '(
        p
        U
        phi
    )'

#- Post process
runApplication postProcess -latestTime -funcs\
    '(
        staticPressure totalPressureIncompressible mag(U)
        patchAverage(p,static(p),total(p),mag(U),name=inlet)
        flowRatePatch(name=inlet)
        angularMomentum
    )'
runApplication -a postProcess -latestTime -funcs\
    '(
        mag(L)
        volIntegrateMagAngularMomentum(name=c0)
        volIntegrateMagAngularMomentum(name=c1)
        volIntegrateMagAngularMomentum(name=c2)
        volIntegrateMagAngularMomentum(name=c3)
        volIntegrateMagAngularMomentum(name=c4)
    )'

#------------------------------------------------------------------------------