#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

./Allmesh

#- Run serial
runApplication $(getApplication)

#- Run parallel
# runApplication decomposePar -force
# runParallel $(getApplication)
# runApplication reconstructPar -latestTime -fields\
#     '(
#         p
#         static(p)
#         total(p)
#         phi
#         U
#         mag(U)
#     )'

#- Post process
runApplication postProcess -latestTime -funcs\
    '(
        patchAverage(p,static(p),total(p),mag(U),name=inlet)
        flowRatePatch(name=inlet)
    )'

#------------------------------------------------------------------------------