#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application=$(getApplication)

runApplication blockMesh
runApplication surfaceFeatureExtract
runApplication snappyHexMesh -overwrite
runApplication checkMesh
runApplication $application

runApplication postProcess -funcs '(patchAverage(p,name=inlet) flowRatePatch(name=inlet))' -latestTime

#------------------------------------------------------------------------------
