#!/bin/bash
#----------------------------------*-sh-*--------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: Addition to OpenFOAM v6
#  \\    /   O peration     | Website:  https://github.com/StasF1/intakePipe
#   \\  /    A nd           | Copyright (C) 2018-2019 Stanislau Stasheuski
#    \\/     M anipulation  |
#------------------------------------------------------------------------------
# License
#     This file is not part of OpenFOAM, but part of intakePipe – OpenFOAM
#     addition.
#
#     intakePipe (like OpenFOAM) is free software: you can redistribute it 
#     and/or modify it under the terms of the GNU General Public License as
#     published by the Free Software Foundation, either ver 3 of the License,
#     or (at your option) any later ver.
#
#     intakePipe (like OpenFOAM) is distributed in the hope that it will be
#     useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#     See the GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this repository. If not, see <http://www.gnu.org/licenses/>
#
# File
#     AllVerRun
#
# Description
#     Run all channel geometry versions (variants)
#
#------------------------------------------------------------------------------

source intakePipeDict

# * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

for (( verNo = 1; verNo <= $versions; verNo++ )); do

    # Copying 0/ folder & verRun script from the ver1/ to the other versions 
    if [[ $verNo>1 ]]; then
        cp -r ver1/verRun ver$verNo/
        cp -r ver1/0 ver$verNo/
    fi

    # Run version (variant) of the inlet channel geometry
    ver$verNo/./verRun

done

#------------------------------------------------------------------------------
